// Bộ hằng số cấu hình giao diện Tailwind CSS cho màn hình Admin Dashboard tổng quan
export const dashboardStyles = {
  container: "space-y-6 p-1",
  titleHeader: "text-2xl font-bold text-slate-800 tracking-tight",
  subtitleHeader: "text-sm text-slate-500 mt-0.5",
  cardGrid: "grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4",
  cardBody: "rounded-xl border border-slate-200 bg-white p-6 shadow-sm flex items-center justify-between",
  cardTitle: "text-xs font-bold text-slate-400 uppercase tracking-wider",
  cardValue: "text-3xl font-extrabold text-slate-800 mt-1",
  cardStatusOn: "text-xs font-bold text-emerald-500 uppercase tracking-normal",
  cardIconBlue: "flex h-12 w-12 items-center justify-center rounded-xl bg-blue-50 text-blue-600 text-xl font-bold",
  cardIconAmber: "flex h-12 w-12 items-center justify-center rounded-xl bg-amber-50 text-amber-600 text-xl font-bold",
  cardIconEmerald: "flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600 text-xl font-bold",
  cardIconIndigo: "flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600 text-xl font-bold",
  tableWrapper: "rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden",
  tableHeaderBar: "border-b border-slate-200 bg-slate-50 px-6 py-4 flex items-center justify-between",
  tableTitle: "text-base font-bold text-slate-800",
  syncButton: "rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-bold text-slate-600 hover:bg-slate-50 shadow-sm transition-all",
  loadingText: "p-12 text-center text-sm font-semibold text-slate-400",
  scrollContainer: "overflow-x-auto",
  mainTable: "w-full text-left border-collapse",
  thRow: "border-b border-slate-200 bg-slate-100 text-xs font-bold uppercase tracking-wider text-slate-500",
  thCell: "px-6 py-3.5",
  tbody: "divide-y divide-slate-200 text-sm font-medium text-slate-600",
  trRow: "hover:bg-slate-50/80 transition-colors",
  tdCell: "px-6 py-4",
  tdCellBold: "px-6 py-4 text-slate-800",
  tdCellMuted: "px-6 py-4 font-semibold text-slate-500",
  tdCellTime: "px-6 py-4 text-xs font-mono text-slate-400",
  badgeCreate: "inline-flex rounded px-2.5 py-0.5 text-xs font-bold font-mono border bg-green-50 text-green-700 border-green-200",
  badgeUpdate: "inline-flex rounded px-2.5 py-0.5 text-xs font-bold font-mono border bg-blue-50 text-blue-700 border-blue-200",
  badgeDelete: "inline-flex rounded px-2.5 py-0.5 text-xs font-bold font-mono border bg-red-50 text-red-700 border-red-200"
};